name: Underdog Church
favicon: null
layout_spectrum: 0.41447
typography_spectrum: 0.832262895302847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#909090'
    - '#bfbfbf'
    - '#4b4b4b'
    - '#323232'
    - '#010101'
  brandStrength: 0.7709456405136734
  lightness: 0.18807955645024776
  saturation: 0.016402914421632886
  rhythmicContrast: 0.5263048291672021
purpose: []
